"""Create authors table with relationships to books table

Revision ID: cfdedd602bcc
Revises: 504fb9f99c08
Create Date: 2024-08-11 16:40:08.935412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfdedd602bcc'
down_revision: Union[str, None] = '504fb9f99c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_foreign_key('author_constraint', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('author_constraint', type_='foreignkey')
    op.drop_table('authors')
    # ### end Alembic commands ###
